-- MySQL Script generated by MySQL Workbench
-- Wed Dec 10 09:12:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `mydb`.`Categories` ;
DROP TABLE IF EXISTS `mydb`.`products` ;
DROP TABLE IF EXISTS `mydb`.`CategoryAttribute` ;
DROP TABLE IF EXISTS `mydb`.`ProductAttribute` ;
DROP TABLE IF EXISTS `mydb`.`Branch` ;
DROP TABLE IF EXISTS `mydb`.`User` ;
DROP TABLE IF EXISTS `mydb`.`Customer` ;
DROP TABLE IF EXISTS `mydb`.`Supplier` ;
DROP TABLE IF EXISTS `mydb`.`Staff` ;
DROP TABLE IF EXISTS `mydb`.`PurchaseOrder` ;
DROP TABLE IF EXISTS `mydb`.`CustomerOrder` ;
DROP TABLE IF EXISTS `mydb`.`Inventory` ;
DROP TABLE IF EXISTS `mydb`.`StockItem` ;
DROP TABLE IF EXISTS `mydb`.`OrderItem` ;
DROP TABLE IF EXISTS `mydb`.`PurchaseItem` ;
DROP TABLE IF EXISTS `mydb`.`StockItemCertificate` ;
SET FOREIGN_KEY_CHECKS=1;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;
-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `parent_category_id` INT NULL,
  `description` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`),
  CONSTRAINT `fk_parent_category`
    FOREIGN KEY (`parent_category_id`)
    REFERENCES `mydb`.`Categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `product_ID` INT AUTO_INCREMENT NOT NULL,
  `sku` VARCHAR(45) UNIQUE NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,  
  `status` ENUM('active', 'discontinued') DEFAULT 'active',
  `unit_price` DECIMAL(10,2) NOT NULL,
  `unit` VARCHAR(20) NULL,
  `description` TEXT NULL,  
  `category_id`    INT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_ID`),
  CONSTRAINT `fk_products_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`Categories` (`category_id`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CategoryAttribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CategoryAttribute` (
  `category_id` INT NOT NULL,
  `attr_name` VARCHAR(50) NOT NULL,
  `data_type` ENUM('text', 'number', 'date', 'boolean', 'color', 'size') DEFAULT 'text',
  `is_required` BOOLEAN DEFAULT FALSE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`, `attr_name`),
  CONSTRAINT `fk_category_attribute`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`Categories` (`category_id`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductAttribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductAttribute` (
  `product_id` INT NOT NULL,
  `attr_name` VARCHAR(50) NOT NULL,
  `attr_value` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_id`, `attr_name`),
  CONSTRAINT `fk_product_attribute_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branch` (
  `branch_ID` INT NOT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(100) UNIQUE NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `manager_ID` INT NULL,  
  `manager_phone` VARCHAR(20) NULL,
  `status` ENUM('active', 'inactive', 'under_renovation') DEFAULT 'active',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`branch_ID`)

) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_ID` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `user_type` ENUM('customer', 'staff', 'supplier', 'CEO') NOT NULL,
  `user_email` VARCHAR(45) UNIQUE NOT NULL,
  `user_telephone` VARCHAR(20) NULL,
  `first_name` VARCHAR(45) NOT NULL, 
  `last_name` VARCHAR(45) NOT NULL, 
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `last_login` DATETIME NULL,
  `is_active` BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (`user_ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_ID` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) , 
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL UNIQUE,
  `gender` VARCHAR(20) NULL,
  `address` VARCHAR(200) NULL,
  `loyalty_level` ENUM('Regular', 'VIP', 'VVIP') DEFAULT 'Regular',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customer_ID`),
  CONSTRAINT `fk_customer_user_name`
    FOREIGN KEY (`user_name`)
    REFERENCES `mydb`.`User` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `supplier_ID` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45),
  `company_name` VARCHAR(100) NOT NULL,
  `contact_person` VARCHAR(100),
  `phone` VARCHAR(20),
  `email` VARCHAR(100),
  `address` VARCHAR(255),
  `tax_number` VARCHAR(50) UNIQUE, 
  `status` ENUM('active', 'inactive') DEFAULT 'active',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`supplier_ID`),
  CONSTRAINT `fk_user_name`
    FOREIGN KEY (`user_name`)
    REFERENCES `mydb`.`User` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `staff_ID` INT NOT NULL AUTO_INCREMENT,
  `branch_ID` INT NOT NULL,
  `user_name` VARCHAR(45), 
  `position` ENUM('Manager', 'Sales', 'Deliveryman') NOT NULL,
  `phone` VARCHAR(20),
  `salary` DECIMAL(10,2) NOT NULL,
  `hire_date` DATE NOT NULL,
  `status` ENUM('active', 'on_leave', 'terminated') DEFAULT 'active',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`staff_ID`),
  CONSTRAINT `fk_staff_user_name`
    FOREIGN KEY (`user_name`)
    REFERENCES `mydb`.`User` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_branch_id`
    FOREIGN KEY (`branch_ID`)
    REFERENCES `mydb`.`Branch` (`branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- 添加外键约束
ALTER TABLE `mydb`.`Branch`
ADD CONSTRAINT `fk_branch_manager`
FOREIGN KEY (`manager_ID`)
REFERENCES `mydb`.`Staff` (`staff_ID`)
ON DELETE SET NULL  
ON UPDATE CASCADE; 

-- -----------------------------------------------------
-- Table `mydb`.`PurchaseOrder`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`PurchaseOrder` (
  `purchase_order_ID` INT NOT NULL AUTO_INCREMENT,
  `supplier_ID` INT NOT NULL, 
  `branch_ID` INT NOT NULL, 
  `date` DATE NOT NULL, 
  `status` ENUM('pending', 'ordered', 'received', 'cancelled') DEFAULT 'pending',
  `total_amount` DECIMAL(10,2) DEFAULT 0,
  PRIMARY KEY (`purchase_order_ID`),
  CONSTRAINT `fk_branch_id`
    FOREIGN KEY (`branch_ID`)
    REFERENCES `mydb`.`Branch` (`branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_id`
    FOREIGN KEY (`supplier_ID`)
    REFERENCES `mydb`.`Supplier` (`supplier_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`CustomerOrder`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`CustomerOrder` (
  `order_ID` INT NOT NULL AUTO_INCREMENT,
  `customer_ID` INT NULL,
  `order_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_ID` INT NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `final_amount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `status` ENUM('Pending','Completed','Cancelled') DEFAULT 'Pending',
  `shipping_address` VARCHAR(255) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_ID`),
  CONSTRAINT `fk_CustomerOrder_branch_id`
    FOREIGN KEY (`branch_ID`)
    REFERENCES `mydb`.`Branch` (`branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomerOrder_customer_id`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `mydb`.`Customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `batch_ID` VARCHAR(20) NOT NULL,
  `product_ID` INT NOT NULL,
  `branch_ID`  INT NOT NULL,
  `locked_inventory` INT NOT NULL DEFAULT 0,
  `quantity_received` INT NOT NULL,
  `quantity_on_hand` INT NOT NULL,
  `unit_cost` DECIMAL(10,2) NOT NULL,
  `received_date` DATE NULL,
  `order_ID` INT NULL,
  `date_produced` DATE NULL,
  `date_expired` DATE NULL,
  PRIMARY KEY (`batch_ID`),
  CONSTRAINT `fk_inventory_branch_id`
    FOREIGN KEY (`branch_ID`)
    REFERENCES `mydb`.`Branch` (`branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_product_id`
    FOREIGN KEY (`product_ID`)
    REFERENCES `mydb`.`products` (`product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_id`
    FOREIGN KEY (`order_ID`)
    REFERENCES `mydb`.`PurchaseOrder` (`purchase_order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StockItem`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`StockItem` (
  `item_ID`  VARCHAR(50) NOT NULL,
  `batch_ID` VARCHAR(20) NOT NULL,
  `product_ID` INT NOT NULL,
  `branch_ID` INT NOT NULL,
  `purchase_order_ID` INT NULL,
  `customer_order_ID` INT NULL,
  `received_date`   DATE NOT NULL,
  `expiry_date`     DATE,
  `status` ENUM('in_stock', 'sold', 'returned', 'damaged','pending') DEFAULT 'in_stock',
  PRIMARY KEY (`item_ID`),
  CONSTRAINT `fk_batch_id`
    FOREIGN KEY (`batch_ID`)
    REFERENCES `mydb`.`Inventory` (`batch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_purchase_order_id`
    FOREIGN KEY (`purchase_order_ID`)
    REFERENCES `mydb`.`PurchaseOrder` (`purchase_order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_customer_order_id`
    FOREIGN KEY (`customer_order_ID`)
    REFERENCES `mydb`.`CustomerOrder` (`order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StockItem_product_id`
    FOREIGN KEY (`product_ID`)
    REFERENCES `mydb`.`products` (`product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StockItem_branch_id`
    FOREIGN KEY (`branch_ID`)
    REFERENCES `mydb`.`Branch` (`branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`PurchaseItem`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`PurchaseItem` (
  `supply_id` INT NOT NULL AUTO_INCREMENT,
  `purchase_order_ID` INT NOT NULL,
  `item_ID` VARCHAR(50) NOT NULL, 
  `product_ID` INT NOT NULL,
  `unit_cost` DECIMAL(10,2) NOT NULL,
  `received_date` DATE NULL,
  PRIMARY KEY (`supply_id`),
  CONSTRAINT `fk_PurchaseItem_product_id`
    FOREIGN KEY (`product_ID`)
    REFERENCES `mydb`.`products` (`product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PurchaseItem_item_id`
    FOREIGN KEY (`item_ID`) 
    REFERENCES `mydb`.`StockItem` (`item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PurchaseItem_order_id`
    FOREIGN KEY (`purchase_order_ID`)
    REFERENCES `mydb`.`PurchaseOrder` (`purchase_order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`OrderItem`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`OrderItem` (
  `order_ID` INT NOT NULL,
  `item_ID` VARCHAR(50) NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,  
  `product_ID` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `status`  VARCHAR(50),
  PRIMARY KEY (`order_ID`, `item_ID`),
  CONSTRAINT `fk_OrderItem_order_id`
    FOREIGN KEY (`order_ID`)
    REFERENCES `mydb`.`CustomerOrder` (`order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_product_id`
    FOREIGN KEY (`product_ID`)
    REFERENCES `mydb`.`products` (`product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_item_ID`
    FOREIGN KEY (`item_ID`)
    REFERENCES `mydb`.`StockItem` (`item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`StockItemCertificate`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`StockItemCertificate` (
  `certificate_ID` INT NOT NULL AUTO_INCREMENT,
  `item_ID` VARCHAR(50) NULL,
  `transaction_type` ENUM('purchase', 'sale', 'return', 'transfer', 'adjustment') NOT NULL, 
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `transaction_ID` INT NULL,
  `note` VARCHAR(200) NULL,
  PRIMARY KEY (`certificate_ID`),
  CONSTRAINT `fk_Stock_item_ID`
    FOREIGN KEY (`item_ID`)
    REFERENCES `mydb`.`StockItem` (`item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;







SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
